export enum EAdminRouteName {
  LIVE_QUEUE_DATA = "Admin - Live Queue Data",
  BANNED_PLAYERS = "Admin - Banned Players",
  SMURF_CHECKER = "Admin - Smurf Checker",
  SMURF_CHECKER_V2 = "Admin - Search Smurfs",
  SMURF_CHECKER_MANAGE_IDENTIFIERS = "Admin - Manage Identifiers",
  GLOBAL_MUTE = "Admin - Global Mute",
  LOUNGE_MUTE = "Admin - Lounge Mute",
  VIEW_GAME_CHAT = "Admin - View Game Chat",
  PROXY_SETTINGS = "Admin - Proxy Settings",
  NEWS = "Admin - News",
  LOADING_SCREEN_TIPS = "Admin - Loading Screen Tips",
  MESSAGE_OF_THE_DAY = "Admin - Message Of The Day",
  ASSIGN_PORTRAITS = "Admin - Assign Portraits",
  MANAGE_PORTRAITS = "Admin - Manage Portraits",
  MANAGE_ALIBABA_FILES = "Admin - Manage Alibaba Files",
  MANAGE_S3_FILES = "Admin - Manage S3 Files",
  MANAGE_MAPS = "Admin - Manage Maps",
  MANAGE_TOURNAMENTS = "Admin - Manage Tournaments",
  MANAGE_PERMISSIONS = "Admin - Manage Permissions",
  VIEW_SERVER_LOGS = "Admin - View Server Logs",
  SERVER_LOG = "Admin - Server Log",
}

export enum EStatisticsRouteName {
  PLAYER_ACTIVITY = "Statistics - Player Activity",
  MMR = "Statistics - MMR",
  WINRATES = "Statistics - Winrates",
  HEROES = "Statistics - Heroes",
}
