import colors from "vuetify/util/colors";

export const human = {
  dark: false,
  colors: {
    primary: "#1976d2",
    secondary: "#424242",
    surface: "rgba(233, 233, 233, 0.9)",
    "w3-gold": "#FFD428",
    "w3-race-bg": "#e9e9e9",
    lost: "#DF323B",
  },
  variables: {
    // "border-color": "#000000",
    // "border-opacity": 0.12,
    // "high-emphasis-opacity": 0.87,
    // "medium-emphasis-opacity": 0.60,
    // "disabled-opacity": 0.38,
    // "idle-opacity": 0.04,
    // "hover-opacity": 0.04,
    // "focus-opacity": 0.12,
    // "selected-opacity": 0.08,
    // "activated-opacity": 0.12,
    // "pressed-opacity": 0.12,
    // "dragged-opacity": 0.08,
    // "theme-kbd": "#212529",
    // "theme-on-kbd": "#FFFFFF",
    // "theme-code": "#F5F5F5",
    // "theme-on-code": "#000000",
  },
};

// Old color classes for reference:
// background: "var(--w3-bg-glass)",
// surface: "var(--v-w3-race-bg-base)",
// card: "var(--w3-bg-glass)",
// toolbar: "var(--v-w3-race-bg-base)",
// "app-bar": "var(--w3-bg-glass)",
// "navigation-drawer": "var(--w3-bg-glass)",
// "bottom-navigation": "var(--v-w3-race-bg-base)",
// "text-primary": "var(--v-w3-race-bg-base)",
// success: "#4caf50",
// black: colors.shades.black,
// white: colors.shades.white,
// "black-gold": colors.shades.black,
// lost: colors.red.darken1,
