export const orc = {
  dark: false,
  colors: {
    primary: "#5c2604",
    "primary-lighten5": "#e3f2fd",
    "primary-darken2": "#1565c0",
    secondary: "#424242",
    accent: "#82B1FF",
    error: "#FF5252",
    info: "#2196F3",
    success: "#4CAF50",
    warning: "#FFC107",
    gold: "#FFD428",
    background: "var(--w3-bg-glass)",
    surface: "var(--v-w3-race-bg-base)",
    "w3-race-bg": "#e9e9e9",
    card: "var(--w3-bg-glass)",
    toolbar: "var(--v-w3-race-bg-base)",
    "app-bar": "var(--w3-bg-glass)",
    "navigation-drawer": "var(--w3-bg-glass)",
    "bottom-navigation": "var(--v-w3-race-bg-base)",
    "text-primary": "var(--v-w3-race-bg-base)",
    "text-secondary": "rgba(0, 0, 0, 0.75)",
  },
};
